export const MOCK_SONGS = [
  {
    id: 1,
    title: "Guess I'll Never Know",
    artist: 'TrackTribe',
    genre: 'Pop',
    duration: 245,
    filePath: 'mock://song1.mp3',
    albumArt: '🎵',
  },
  {
    id: 2,
    title: 'My Day',
    artist: 'Bah Tung MTP',
    genre: 'Electronic',
    duration: 198,
    filePath: 'mock://song2.mp3',
    albumArt: '🎵',
  },
  {
    id: 3,
    title: 'Eternal',
    artist: 'Karot Sandar',
    genre: 'Ambient',
    duration: 320,
    filePath: 'mock://song3.mp3',
    albumArt: '🎵',
  },
  {
    id: 4,
    title: 'Coffee',
    artist: 'Firewalker',
    genre: 'Jazz',
    duration: 215,
    filePath: 'mock://song4.mp3',
    albumArt: '☕',
  },
  {
    id: 5,
    title: 'Dreamer',
    artist: 'GossieRerry',
    genre: 'Pop',
    duration: 267,
    filePath: 'mock://song5.mp3',
    albumArt: '🎵',
  },
  {
    id: 6,
    title: 'Đừng Làm Trái Tim Anh Đau',
    artist: 'TrackTribe',
    genre: 'Pop',
    duration: 280,
    filePath: 'mock://song6.mp3',
    albumArt: '💔',
  },
];

export const MOCK_PLAYLISTS = [
  { id: 1, name: 'Chill 😎', description: 'Relaxing vibes', coverImage: '😎' },
  { id: 2, name: 'Playlist #1', description: '', coverImage: '🎵' },
  { id: 3, name: 'Playlist #2', description: '', coverImage: '🎵' },
  { id: 4, name: 'Playlist #3', description: '', coverImage: '🎵' },
  { id: 5, name: 'Playlist #4', description: '', coverImage: '🎵' },
  { id: 6, name: 'Playlist #6', description: '', coverImage: '🎵' },
];
